default: fmt fix

# Startup commands
dev host="127.0.0.1" port="8000":
    uv run uvicorn src.main:app --host {{host}} --port {{port}} --reload

# Code quality commands
fmt:
    uv run ruff format

check-fmt:
    uv run ruff format --check

lint:
    uv run ruff check

fix:
    uv run ruff check --fix
